name: brightfield-analysis-env
channels:
  - conda-forge
dependencies:
  - python=3.13
  - napari==0.5.0
  - pyqt==5.15.10
  - apoc-backend==0.12.0
  - napari-simpleitk-image-processing==0.4.9
  - napari-skimage-regionprops==0.10.1
  - natsort==8.4.0
  - scikit-image==0.25.1
  - json5==0.10.0
  - pandas==2.2.3
  - seaborn==0.13.2 
  - simpleitk==2.4.1
  - watermark
  - jupyterlab
  - pip
  - pip:
    - pyclesperanto-prototype==0.24.4
    - watermark[gpu]